eclipse-corrosion/corrosion

org.eclipse.redox/grammar/Rust.tmLanguage
org.eclipse.redox/src/org/eclipse/redox/RLSClientImplementation.java
target-platform/target-platform.target

- Added syntax highlighting for lifetimes, e.g. &'static, 'a
- Updated target file for lsp4e to make Travis CI build
- Removed race condition from RLSClientImplementation to make Travis CI pass

Issue #14 Syntax highlighting issue

---

org.eclipse.redox/src/org/eclipse/redox/debug/ToggleBreakpointsTargetFactory.java

Issue #25: Error when using with JDT and Enhanced Class Decompiler

---

.project
.settings/org.eclipse.m2e.core.prefs
org.eclipse.corrosion.tests/.classpath
org.eclipse.corrosion.tests/.project
org.eclipse.corrosion.tests/.settings/org.eclipse.m2e.core.prefs
org.eclipse.corrosion/.classpath
org.eclipse.corrosion/.gitignore
org.eclipse.corrosion/.project
org.eclipse.corrosion/.settings/org.eclipse.m2e.core.prefs
target-platform/.gitignore
target-platform/.project
target-platform/.settings/org.eclipse.m2e.core.prefs

Added settings for m2e execution. Also updatet gitignore for the ouput folder of maven. Should fix #29

M2E settings

---

org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPreferencePage.java
org.eclipse.corrosion/src/org/eclipse/corrosion/RustGDBLaunchWrapper.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugTabGroup.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/SourceLookupDirector.java

- Auto set the gdb to rust-gdb

Issue #50 Use the rust-gdb with pretty print for debug

---

org.eclipse.corrosion/plugin.xml
org.eclipse.corrosion/src/org/eclipse/corrosion/cargo/core/CLIOption.java
org.eclipse.corrosion/src/org/eclipse/corrosion/cargo/core/CargoTools.java
org.eclipse.corrosion/src/org/eclipse/corrosion/cargo/ui/OptionLabelProvider.java
org.eclipse.corrosion/src/org/eclipse/corrosion/cargo/ui/OptionSelector.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java
org.eclipse.corrosion/src/org/eclipse/corrosion/test/CargoTestDelegate.java
org.eclipse.corrosion/src/org/eclipse/corrosion/test/CargoTestTab.java
org.eclipse.corrosion/src/org/eclipse/corrosion/test/CargoTestTabGroup.java
org.eclipse.corrosion/src/org/eclipse/corrosion/wizards/export/CargoExportWizard.java
org.eclipse.corrosion/src/org/eclipse/corrosion/wizards/newCargo/NewCargoProjectWizard.java

- New run configuration for running tests
- New dialog for selecting options from cargo commands
- Moved common cargo logic to single file

Issue #37 Test Support

---

pom.xml

Change-Id: I85a792af73b892bc0f2882ea5f6a25c1dc7177f2

Fix scmUrl.

---

org.eclipse.corrosion.tests/META-INF/MANIFEST.MF
org.eclipse.corrosion.tests/OSGI-INF/l10n/bundle.properties
org.eclipse.corrosion.tests/build.properties
org.eclipse.corrosion/META-INF/MANIFEST.MF
org.eclipse.corrosion/OSGI-INF/l10n/bundle.properties
org.eclipse.corrosion/build.properties
org.eclipse.corrosion/plugin.xml
pom.xml

Localization missing and encoding not explicit.
Change-Id: I6fc5af51430631f13afc1b881180e40ecaba1b6d

Fix tycho warnings.

---

target-platform/target-platform.target

Not used for anything.
Change-Id: I455301f8450352fcc7879b2bffc1faacc94cd5cd

Remove mylyn deps from target platform.

---

org.eclipse.corrosion/src/org/eclipse/corrosion/Messages.java
org.eclipse.corrosion/src/org/eclipse/corrosion/messages.properties
org.eclipse.corrosion/src/org/eclipse/corrosion/run/CargoRunDelegate.java

Issue #74: Can't launch rust project

---

org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java
org.eclipse.corrosion/src/org/eclipse/corrosion/launch/RustLaunchDelegateTools.java
org.eclipse.corrosion/src/org/eclipse/corrosion/run/CargoRunDelegate.java
org.eclipse.corrosion/src/org/eclipse/corrosion/test/CargoTestDelegate.java

- Moved duplicate code to helper class
- Unable to make an abstract class with content due to
RustDebugDelegate already extending GDBLaunchDelegate

Issue #73 - Better factorize various LaunchConfig classes

---

Jenkinsfile
org.eclipse.corrosion.tests/src/org/eclipse/corrosion/tests/TestLSPExtensions.java
org.eclipse.corrosion.tests/src/org/eclipse/corrosion/tests/TestNewCargoProjectWizard.java
org.eclipse.corrosion/src/org/eclipse/corrosion/CommandJob.java
org.eclipse.corrosion/src/org/eclipse/corrosion/RustManager.java
org.eclipse.corrosion/src/org/eclipse/corrosion/snippet/Snippet.java
org.eclipse.corrosion/src/org/eclipse/corrosion/wizards/newproject/NewCargoProjectWizard.java

- Update Jenkins file to include SonarQube login
- Unconfirmed, creating pull request to test

Issue #83 - Enable analysis with SonarQube

---

pom.xml

Update tycho version to 1.2.0

---

org.eclipse.corrosion/OSGI-INF/l10n/bundle.properties
org.eclipse.corrosion/plugin.xml
org.eclipse.corrosion/src/org/eclipse/corrosion/Messages.java
org.eclipse.corrosion/src/org/eclipse/corrosion/messages.properties
org.eclipse.corrosion/src/org/eclipse/corrosion/wizards/importexisting/ImportPage.java
org.eclipse.corrosion/src/org/eclipse/corrosion/wizards/importexisting/ImportWizard.java

- Added a new import wizard
- Does not link to but instructs the user how to get to the correct
import wizard

Issue #92 Import wizard teaching proper flow

---

org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPreferenceInitializer.java

Signed-off-by: Holger Voormann <github@voormann.de>

Issue #86 Set correct default locations on Windows

---

org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java

- Move the configuration variable parsing to getLaunch() instead of
launch() ensuring that the launch and confiuraiton are in sync

Issue #106 Fix for 99 breaks debugging

---

org.eclipse.corrosion/META-INF/MANIFEST.MF
org.eclipse.corrosion/language-configurations/language-configuration.json
org.eclipse.corrosion/plugin.xml
target-platform/target-platform.target

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17344
following commit https://github.com/eclipse/tm4e/commit/2bce39b064ec8ecc88d3667ada6282db369d36a6)

Add language configuration support

---

org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugTabGroup.java

Add Arguments tab to debug tab group.

---

Jenkinsfile

Fixing zipped repository structure

---

org.eclipse.corrosion/snippets/rust.json

Added text templates for quick creation of test methods and test
modules.

Templates for test cases and test modules

---

org.eclipse.corrosion.tests/src/org/eclipse/corrosion/tests/TestNewCargoProjectWizard.java

Do not delete .cargo during tests

---

org.eclipse.corrosion.feature/feature.xml
org.eclipse.corrosion.feature/pom.xml
org.eclipse.corrosion.tests/META-INF/MANIFEST.MF
org.eclipse.corrosion.tests/pom.xml
org.eclipse.corrosion/META-INF/MANIFEST.MF
org.eclipse.corrosion/pom.xml
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugTab.java
pom.xml
repository/pom.xml
target-platform/pom.xml

Fix #188 - Remove duplicate Working Directory from main tab

---

Jenkinsfile

Refer to workspace/.m2e.

---

pom.xml

Jacoco 0.8.2 requires Maven 3.3.9.

Set correct min Maven version.

---

org.eclipse.corrosion.feature/feature.xml
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustGDBLaunchWrapper.java
target-platform/target-platform.target

Fix debug launch

---

pom.xml

Enable reproducible version qualifiers

---

org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPlugin.java
org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPreferenceInitializer.java
org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPreferencePage.java
org.eclipse.corrosion/src/org/eclipse/corrosion/RustManager.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustGDBLaunchWrapper.java

Fix #202 - Cannot use Rust if installed in directories containing spaces

---

documentation/Troubleshooting.md

Signed-off-by: Nicola Orru <nigu.orru@gmail.com>
First pass of troubleshooting guide

Troubleshooting guide

---

org.eclipse.corrosion/src/org/eclipse/corrosion/launch/RustLaunchDelegateTools.java

Needed so finding existing launch configs work proper.

Fix RustLaunchDelegate to consider CDT and corrosion project attributes

---

org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java

Add Crate name to Rust main breakpoint

---

org.eclipse.corrosion/plugin.xml

(ctrl+/) and (didSave)
Signed-off-by: Nico Orru <nigu.orru@gmail.com>

Fix for #215 and https://github.com/rust-lang/rls/issues/1240

---

org.eclipse.corrosion/src/org/eclipse/corrosion/edit/RLSStreamConnectionProvider.java

Signed-off-by: Nicola Orru <nigu.orru@gmail.com>

Removed transitional goto_def_racer_fallback; demoted  warning

---

org.eclipse.corrosion/META-INF/MANIFEST.MF
org.eclipse.corrosion/src/org/eclipse/corrosion/snippet/Snippet.java
repository/category.xml
target-platform/target-platform.target

Update TP for 2019-03

---

documentation/Troubleshooting.md

Signed-off-by: Nicola Orru <nigu.orru@gmail.com>
- Minor documentation updates

Updated troubleshooting guide with references to 2019-03

---

pom.xml

And fix warning about not set version for tycho-packaging-plugin.

Update to Tycho 1.4.0

---

pom.xml

Update to jacoco 0.8.3

---

org.eclipse.corrosion.feature/feature.xml
org.eclipse.corrosion.feature/pom.xml
org.eclipse.corrosion/META-INF/MANIFEST.MF
org.eclipse.corrosion/pom.xml
pom.xml
target-platform/target-platform.target

Build against 2019-06

---

org.eclipse.corrosion/plugin.xml
org.eclipse.corrosion/src/org/eclipse/corrosion/ErrorLineMatcher.java

Add console hyperlinks for errors.

---

org.eclipse.corrosion/src/org/eclipse/corrosion/ui/launch/AbstractCargoLaunchConfigurationTab.java

There is no need for border in the tab.
Fixes #256

Strange border in run view

---

org.eclipse.corrosion/src/org/eclipse/corrosion/ErrorLineMatcher.java

Fix console hyperlinks with debug launches.

---

Jenkinsfile
org.eclipse.corrosion.feature/feature.xml
org.eclipse.corrosion.feature/pom.xml
org.eclipse.corrosion.tests/META-INF/MANIFEST.MF
org.eclipse.corrosion.tests/pom.xml
org.eclipse.corrosion/META-INF/MANIFEST.MF
org.eclipse.corrosion/pom.xml
pom.xml
repository/pom.xml
target-platform/pom.xml
target-platform/target-platform.target

Update target platform to build against 2019-12

---

org.eclipse.corrosion/src/org/eclipse/corrosion/snippet/Snippet.java

- Removed call to LSPDocumentInfo#getLanguageClient by call to
LSPDocumentInfo#getInitializedLanguageClient

Exchange call to deprecated LSP4E method

---

README.md
documentation/Troubleshooting.md

- Update installation instructions to include rustup instructions,
avoiding paper cuts during setup
- Added section to troubleshoot guide for debugging on Windows,
extracted from knowledge scattered over the issue tracker

Little documentation enhancements

---

org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPreferenceInitializer.java
org.eclipse.corrosion/src/org/eclipse/corrosion/Messages.java
org.eclipse.corrosion/src/org/eclipse/corrosion/RustManager.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/DebugPreferencePage.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/DebugUtil.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugTabGroup.java
org.eclipse.corrosion/src/org/eclipse/corrosion/messages.properties

- Added properties entry for default Rust GDB
- Using this GDB as the default for new Rust debug launch configs

Issue #295 - Preference for default Rust debugger

---

target-platform/Corrosion.setup

Sets up dev environment for Corrosion as would be done manually.
This is the first step for Issue #301.

Oomph setup for setting up dev environment and target definition

---

target-platform/Corrosion.setup

Mapping the setup URL from GitHub link to local git repository fixed.

#301 Fixing ULR mapping in Oomph setup

---

README.md

Also updated the marketplace link.

Updated README.md to point to latest EPP package download

---

Jenkinsfile
pom.xml

Adapt Jenkinsfile for new infra

---

Jenkinsfile
target-platform/target-platform.target

Change-Id: I7aef71f96d9fae12ceba7a1d3c08585c49ee926e

Try logging tests

---

Jenkinsfile

Fix snapshot deploy for new infra.

---

Jenkinsfile

Fix genie name in deploy step.

---

org.eclipse.corrosion.tests/META-INF/MANIFEST.MF

There is no need for fragment to require its host.

---

target-platform/target-platform.target

Enhance target platform to allow running tests with it.

---

pom.xml

Build with Tycho 2.0.0

---

.mvn/extensions.xml
pom.xml

Switch tycho pomless to 2.0.0

---

org.eclipse.corrosion.tests/src/org/eclipse/corrosion/tests/TestErrorLineMatcher.java
org.eclipse.corrosion/META-INF/MANIFEST.MF
org.eclipse.corrosion/src/org/eclipse/corrosion/ErrorLineMatcher.java

Issue #334 -  NumberFormatException at ErrorLineMatcher

---

.mvn/extensions.xml

Switch pomless to Tycho 2.1.0.

---

Jenkinsfile
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java
org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustGDBLaunchWrapper.java

Attempt fixing test on CI (cont'd)

---

repository/category.xml

So it can be resolved at install-time.

Add unittest bundle to dependencies

---

target-platform/target-platform.target

Use Platform 4.18-RC2 repository

---

Jenkinsfile

Build with centos 8.

---

org.eclipse.corrosion.product.branding/META-INF/MANIFEST.MF
org.eclipse.corrosion.product.branding/pom.xml
repository/corrosion.product
repository/pom.xml

Fix versions to 1.1.1

---

org.eclipse.corrosion.tests/src/org/eclipse/corrosion/tests/TestDebugConfiguration.java
org.eclipse.corrosion/src/org/eclipse/corrosion/resources/ResourceLookupTree.java
org.eclipse.corrosion/src/org/eclipse/corrosion/sourcelookup/CargoProjectSourceContainerType.java
org.eclipse.corrosion/src/org/eclipse/corrosion/sourcelookup/CargoSourceUtils.java

Code cleanups

---

NOTICE.md
README.md
documentation/Troubleshooting.md
pom.xml
repository/corrosion.product

Use https for downloads

---

org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPlugin.java
org.eclipse.corrosion/src/org/eclipse/corrosion/RustManager.java
org.eclipse.corrosion/src/org/eclipse/corrosion/edit/RLSStreamConnectionProvider.java
org.eclipse.corrosion/src/org/eclipse/corrosion/extensions/ImplementationsSearchQuery.java
org.eclipse.corrosion/src/org/eclipse/corrosion/launch/LaunchHandler.java
org.eclipse.corrosion/src/org/eclipse/corrosion/sourcelookup/CargoProjectSourceContainer.java
org.eclipse.corrosion/src/org/eclipse/corrosion/sourcelookup/CargoSourceUtils.java
org.eclipse.corrosion/src/org/eclipse/corrosion/wizards/newproject/NewCargoProjectWizard.java

Ensures that correct plugin ids are used as right now claiming issue
comes from LSP4E bundle in some places is misleading.

Simplify Status creation

---

org.eclipse.corrosion/language-configurations/language-configuration.json

See https://code.visualstudio.com/api/language-extensions/language-configuration-guide

Fix onEnterRules syntax in language configuration

---

Jenkinsfile
repository/pom.xml

PGP sign with bouncycastle
