org.eclipse.corrosion/plugin.xml, org.eclipse.corrosion/src/org/eclipse/corrosion/TextEditorPreferencePage.java
- Instead of implementing hack workaround or pushing rls to ignore
valid parameters
- Explicit point users to Text Editors preference page for updating tab
defaults
- Also point users to editing fonts and highlighting
=> Issue #39: Ensure spaces are being used instead of tabs in formatting

org.eclipse.corrosion/src/org/eclipse/corrosion/RustGDBLaunchWrapper.java
Which command doesn't exist on windows so better to rely on where
(should give full path to gdb executable if on syspath).
Should improve #64 on windows.
=> Use 'where' instead of 'which' on Windows.

org.eclipse.corrosion.tests/META-INF/MANIFEST.MF, org.eclipse.corrosion.tests/src/org/eclipse/corrosion/tests/AllTests.java, org.eclipse.corrosion.tests/src/org/eclipse/corrosion/tests/TestSnippetContentAssistProcessor.java, org.eclipse.corrosion/META-INF/MANIFEST.MF, org.eclipse.corrosion/src/org/eclipse/corrosion/snippet/SnippetContentAssistProcessor.java
- Check to see if the cursor is in a Rust comment or not before
returning snippet completions
=> #79 - Prevent competion assist in comments

org.eclipse.corrosion/grammar/Rust.tmLanguage
Before maybe switching to a new grammar, this commit fixes syntax
coloration of raw strings. There can be a flexible amount of '#'
delimiters at the start and end of a raw string. This allows arbitrary
characters in the string (except the end sequence of " and the same
amount of '#' characters as in the beginning). For more info see:
https://doc.rust-lang.org/reference/tokens.html#characters-and-strings
=> Temporary fix for raw strings

org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java, org.eclipse.corrosion/src/org/eclipse/corrosion/launch/RustLaunchDelegateTools.java, org.eclipse.corrosion/src/org/eclipse/corrosion/run/CargoRunDelegate.java, org.eclipse.corrosion/src/org/eclipse/corrosion/test/CargoTestDelegate.java
* Previously it was assumed that projects are physically stored below
the workspace directory. When projects are located e.g. in a git
repository and imported into the workspace this assumption does not
hold. This was fixed with a proper lookup.
* Changed API of the convertToAbsolutePath method to take a string
instead of a file, since all callers had to create a file from a
string anyway.
=> Fixed absolute path calculation for workspace resources

org.eclipse.corrosion/src/org/eclipse/corrosion/launch/RustLaunchDelegateTools.java
Sorry, this should have been part of my last pull request.
convertToAbsolutePath is now taking path directly in relative path case
instead of converting file back to a relative path string.
=> Tiny improvement over PR #148

org.eclipse.corrosion/src/org/eclipse/corrosion/debug/DebugUtil.java, org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java, org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugTab.java, org.eclipse.corrosion/src/org/eclipse/corrosion/launch/RustLaunchDelegateTools.java
Unfortunately this does not fix the Problem that rust does not ship a working version of the rust-gdb wrapper for Windows, but this is a more difficult issue and I am not convinced a workaround should be put into Corrosion.
* Computing the default executable path on Windows now returns a path
with the ".exe" suffix. This heuristic approach falls short when a
rust toolchain for a different platform is selected (for cross-
compilation). In future the location could be determined by the
currently selected rust toolchain.
* Added a null-check to prevent a NullPointerException on non-existent
workspace resources. This exception would silently be swallowed
without feedback to the user.
=> Smoother debug program default for Windows OS

org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPlugin.java, org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java
When looking up the GDB version fails, the cause is now logged.
This can be used to gain insight what goes wrong on user's machines.
Currently it seems very much unclear what is happening here.
=> Added logging of status when determining GDB version fails

org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java
=> Fix #209 - Rust Debug configuration is not being added to the Debug History

org.eclipse.corrosion/src/org/eclipse/corrosion/run/CargoRunDelegate.java, org.eclipse.corrosion/src/org/eclipse/corrosion/test/CargoTestDelegate.java
It is standard in Eclipse to have the launch config saved on first run.
=> Always save the launch configuration for run and test.

org.eclipse.corrosion/plugin.xml, org.eclipse.corrosion/src/org/eclipse/corrosion/ErrorLineMatcher.java
Avoids the +/-4 calculations in the code. Thanks Max Bureck for teaching
me.
=> Use better regex in the error line matcher.

org.eclipse.corrosion/src/org/eclipse/corrosion/run/CargoRunDelegate.java
Fixes #269
@akurtakov , @mickaelistria if you know a better way to get to the env variable configuration without using DebugPlugin, let me know.
=> Run config now takes environment variable config into account

org.eclipse.corrosion.tests/src/org/eclipse/corrosion/tests/TestLSPIntegration.java, org.eclipse.corrosion/pom.xml, org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPreferencePage.java
- Updated rustup shell script to current version 1.20.2 see CQ:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21017
- Updated call to script to install the rls component with rustup
=> Issue #280 - Update rustup shell script and install RLS by default

org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPlugin.java, org.eclipse.corrosion/src/org/eclipse/corrosion/Messages.java, org.eclipse.corrosion/src/org/eclipse/corrosion/debug/DebugUtil.java, org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java, org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugTab.java, org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugTabGroup.java, org.eclipse.corrosion/src/org/eclipse/corrosion/messages.properties
This commit fixes #178 and streamlines the debug launch tabs a bit.
Now the Rust debug launch config checks if the specified GDB is valid.
This is done in a blocking fashion, tests show that this does not block
the UI for an unreasonable time. Making the check non-blocking would
also make the code much more complicated, since the launcher framework
does not seem to be fit for such things.
Also some cosmetic changes were done to the debug launch config. The
"Main" tab now starts with a capital letter, as all other tabs. It also
has an icon now.
=> GDB check in launch config

org.eclipse.corrosion.tests/META-INF/MANIFEST.MF, org.eclipse.corrosion.tests/src/org/eclipse/corrosion/launch/CargoArgsTest.java, org.eclipse.corrosion.tests/src/org/eclipse/corrosion/launch/RLSRunCommandTest.java, org.eclipse.corrosion.tests/src/org/eclipse/corrosion/tests/AllTests.java, org.eclipse.corrosion/plugin.xml, org.eclipse.corrosion/src/org/eclipse/corrosion/ErrorLineMatcher.java, org.eclipse.corrosion/src/org/eclipse/corrosion/Messages.java, org.eclipse.corrosion/src/org/eclipse/corrosion/debug/RustDebugDelegate.java, org.eclipse.corrosion/src/org/eclipse/corrosion/edit/RLSStreamConnectionProvider.java, org.eclipse.corrosion/src/org/eclipse/corrosion/launch/CargoArgs.java, org.eclipse.corrosion/src/org/eclipse/corrosion/launch/LaunchHandler.java, org.eclipse.corrosion/src/org/eclipse/corrosion/launch/RLSRunCommand.java, org.eclipse.corrosion/src/org/eclipse/corrosion/launch/RustLaunchDelegateTools.java, org.eclipse.corrosion/src/org/eclipse/corrosion/messages.properties, org.eclipse.corrosion/src/org/eclipse/corrosion/run/CargoRunDelegate.java, org.eclipse.corrosion/src/org/eclipse/corrosion/test/CargoTestDelegate.java
Added LaunchHandler to handle RLS "rls.run" LSP commands. These
are attached to the "Run test" CodeLens message. And invoked by the
user by clicking on the CodeMining created for the CodeLens.
The LaunchHandler will try to find a cargo test launch config for the
command parameters, if no launch config is found, it a new launch config
will be created (but not saved). The launch config will then be started.
=> Issue #278 "Run test" CodeMining

NOTICE.md
The copyright notices were a bit out of date and had incomplete
licensing information.
=> Updated copyright notices

org.eclipse.corrosion/snippets/rust.json, org.eclipse.corrosion/src/org/eclipse/corrosion/snippet/Snippet.java, org.eclipse.corrosion/src/org/eclipse/corrosion/snippet/SnippetContentAssistProcessor.java
Adjusted SnippetContentAssistProcessor to create Range from editor text
selection (if present and non-empty) for TextEdit, so templates with
$TM_SELECTED_TEXT are able to sourround the selection.
=> Implement "sourround with" style templates

NOTICE.md, org.eclipse.corrosion/grammar/rust.tmLanguage.json
Updated Rust grammar definition from VS Code project.
CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21345
This time an unmodified version of the file plus an update of the
NOTICE.md file explaining the chain of origins.
=> Update rust.tmLanguage.json file

CONTRIBUTING.md, README.md, documentation/Changelog.md
Changelog with significant user-facing changes was extracted from
the git version history.
=> Added a changelog with information extracted from version history

.mvn/extensions.xml, launch/corrosion_build_nix.launch, launch/corrosion_build_win.launch, pom.xml
Update to Tycho 1.6.0 since it speeds up the build 🏎.
Also added external tool launch configurations to start build with mvnw.
=> Update to Tycho 1.6.0 for performance reasons

target-platform/Corrosion.setup
This change is done to allow git clone without SSH or GitHub account.
New users can get up and running faster this way.
=> #301 Switch Oomph setup git URI to HTTPS

target-platform/Corrosion.setup
Changing the logical parent to Eclipse projects for preparation for
inclusion into the central Oomph project catalogue.
=> Issue #301 Preparation for inclusion in central Eclipse Projects index

org.eclipse.corrosion/src/org/eclipse/corrosion/CorrosionPreferenceInitializer.java, org.eclipse.corrosion/src/org/eclipse/corrosion/edit/RLSStreamConnectionProvider.java
Now in the preferences, the location to an rls.conf file will be empty.
An empty string will now skip configuration loading and create a
default initialization configuration.
This will prevent log messages about a missing config file by default,
since the RLS does not ship with an rls.config anymore. Unfortunately,
the RLS does not document at all how an
InitializeParams#initializationOptions message looks like, so we cannot
reference from the Corrosion document to an RLS page explaining the
content of an rls.conf file.
=> Issue #299 Defaulting to empty RLS config file path

target-platform/CorrosionConfiguration.setup
The eclipse installer allows registering the protocol eclipse+installer
to handle installations via web links. The link must point to an Oomph
model containing an Oomph Configuration element. This configuration
information which eclipse product and which project is selected in the
Eclipse installer.
The same link can also be dropped onto the installer, if registering
the protocol is not wanted.
This commit prepares such a Configuration model.
=> Issue #301 Preparation for eclipse+installer link.

CONTRIBUTING.md
The CONTRIBUTING.md file is now updated to point out how to install
an IDE for working on Corrosion. This now includes the Oomph based
installation and setup of an Eclipse Instance via the installer or
project import via Oomph.
=> Issue #301 Update of documentation for setting up an IDE for Corrosion

pom.xml, target-platform/target-platform.target
The 4.18milestones repo is gone so without this one build is broken.
Needs bump to Tycho 2.2.0-SNAPSHOT for the JUnit 5.7 support.
=> Build against 2020-12 Eclipse release

pom.xml
Corrosion is mainly shipped by the IDE, which does include Java 14 and
thus is not compatible with pack200.
Let's simplify things and get rid of pack200, assuming the majority of
users are using Java 14+
=> Remove pack200 stuff

org.eclipse.corrosion/plugin.xml
Since move to rust-analyzer, the state of .toml files shouldn't be sent
to the Language Server, or rust-analyzer will try to parse them as Rust
file and report loads of unrelated errors.
=> Issue #383 - Un-associate LS with Cargo.toml by default
